In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Assignment_LR.csv")

In [10]:
df.head(10)

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

In [7]:
df['Weight'].mean()

4.571428571428571

In [9]:
df['Price'].mean()

47.142857142857146

In [11]:
x = df['Weight']
y = df['Price']

In [12]:
x

0    2
1    4
2    5
3    3
4    6
5    5
6    7
Name: Weight, dtype: int64

In [13]:
y

0    35
1    60
2    20
3    50
4    50
5    55
6    60
Name: Price, dtype: int64

In [14]:
type(x)

pandas.core.series.Series

In [15]:
type(y)

pandas.core.series.Series

### Manual

In [16]:
x.mean()

4.571428571428571

In [17]:
y.mean()

47.142857142857146

In [18]:
import numpy as np

In [19]:
dev_x = x-x.mean()
dev_y = y-y.mean()

In [20]:
dev_x

0   -2.571429
1   -0.571429
2    0.428571
3   -1.571429
4    1.428571
5    0.428571
6    2.428571
Name: Weight, dtype: float64

In [21]:
dev_y

0   -12.142857
1    12.857143
2   -27.142857
3     2.857143
4     2.857143
5     7.857143
6    12.857143
Name: Price, dtype: float64

In [22]:
m = np.sum(dev_x * dev_y) / np.sum(dev_x ** 2)

In [23]:
m

2.620967741935484

In [25]:
c = y.mean()- (m*x.mean()) 

In [26]:
c

35.16129032258065

In [27]:
c = np.mean(y) - m*np.mean(x)

In [28]:
c

35.16129032258065

In [29]:
# y = mx + c
# y = 2.620967741935484x + 35.16129032258065
2.620967741935484 * 6 + 35.16129032258065

50.88709677419355

### using sklearn

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
reg = LinearRegression()

In [43]:
reg.fit(df[['Weight']], df['Price'])

LinearRegression()

In [44]:
reg.coef_

array([2.62096774])

In [45]:
reg.intercept_

35.16129032258065

In [46]:
2.62096774 * 6 + 35.16129032258065

50.88709676258065

In [54]:
m = reg.coef_
c = reg.intercept_
m * 2 + c

array([40.40322581])

In [55]:
m * 4 + c

array([45.64516129])

In [56]:
m * 6 + c

array([50.88709677])

In [60]:
reg.predict(df[["Weight"]])

array([40.40322581, 45.64516129, 48.26612903, 43.02419355, 50.88709677,
       48.26612903, 53.50806452])

In [61]:
df["Predicted"] = reg.predict(df[["Weight"]])

In [62]:
df

Weight  Price  Predicted
0       2     35  40.403226
1       4     60  45.645161
2       5     20  48.266129
3       3     50  43.024194
4       6     50  50.887097
5       5     55  48.266129
6       7     60  53.508065

### Residual

In [63]:
df['residual'] = df['Price'] - df['Predicted']

In [64]:
df

Weight  Price  Predicted   residual
0       2     35  40.403226  -5.403226
1       4     60  45.645161  14.354839
2       5     20  48.266129 -28.266129
3       3     50  43.024194   6.975806
4       6     50  50.887097  -0.887097
5       5     55  48.266129   6.733871
6       7     60  53.508065   6.491935

### MSE

In [65]:
from sklearn.metrics import mean_squared_error

In [69]:
mse = mean_squared_error(df['Price'], df['Predicted'])

In [70]:
mse

167.30990783410135

### MAE

In [72]:
from sklearn.metrics import mean_absolute_error

In [74]:
mae = mean_absolute_error(df['Price'], df['Predicted'])

In [75]:
mae

9.87327188940092

### RMSE

In [76]:
from math import sqrt

In [77]:
rmse = sqrt(mse)

In [78]:
rmse

12.934833119685052